apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: localhost/nginx:latest
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: serve
          mountPath: /serve
        - name: nginx-conf
          mountPath: /conf/nginx.conf
          subPath: nginx.conf
  volumes:
    - name: serve
      hostPath:
        path: /Users/rahulmnavneeth/projects/podman-nix/serve
        type: Directory
    - name: nginx-conf
      hostPath:
        path: /Users/rahulmnavneeth/projects/podman-nix/config
        type: Directory
